spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS2022;databaseName=HotelReservationDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Hotel@1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080